### ISSUE TITLE
HasOptions 函数问题

### ISSUE THREAD

**Issue by kbdxbt** [guanguans/soar-php#150]
https://github.com/guanguans/soar-php/blob/6c4564b146057a628e5fc02c9c0199b857655aba/src/Concerns/HasOptions.php#L1556

这段代码有个问题，就是因为的 database 参数是 test，然后laravel助手函数中又包含 test 函数，这样导致执行出现了异常。
这里是否考虑加上 is_object 去判断是否是匿名函数

**Comment by guanguans** [comment]
@kbdxbt 不好意思我刚看到。从回调类型中排除是函数的应该就可以了。我有时间改一下。

**Comment by kbdxbt** [comment]
> @kbdxbt不好意思我刚看到。从回调类型中排除是函数应该就可以了。我有时间改一下。

好的，我也是偶然发现这个问题，我本地使用了“test“名称的数据库，刚好pest里面也有这个助手函数，就触发了这个问题。
