### ISSUE TITLE
执行 explain 的时候没有做判空处理

### ISSUE THREAD

**Issue by kamly** [guanguans/soar-php#8]
**Describe the bug**
执行 explain 的时候没有做判空处理 

**To Reproduce**
$soar = new Soar($config);
$sql = "select * from `user_notifications`;
$soar->explain($sql, 'md');

**Expected behavior**
PHP Notice:  Undefined index: partitions in ./vendor/guanguans/soar-php/src/PDO.php on line 71
PHP Notice:  Undefined index: filtered in ./vendor/guanguans/soar-php/src/PDO.php on line 78

**Comment by guanguans** [comment]
@kamly 可否修复一下 pr 过来。

**Comment by guanguans** [comment]
@all-contributors please add @kamly for bug

**Comment by kamly** [comment]
@guanguans 是否设置了禁止提交的权限？ 

remote: Permission to guanguans/soar-php.git denied to kamly.
fatal: unable to access 'https://github.com/guanguans/soar-php.git/': The requested URL returned error: 403

**Comment by guanguans** [comment]
@kamly 没有哈，你再试试

**Comment by kamly** [comment]
还是一样... 我 push 到自己的仓库是可以的

**Comment by guanguans** [comment]
@kamly 你直接 `push` 到我的仓库肯定是没有权限的，可参考 [https://juejin.im/post/5ad...](https://juejin.im/post/5adb3da06fb9a07ab110bfcc) 这篇文章，修复代码后 `Pull request` 过来，我这边就可以合并了，幸苦了。
