### ISSUE TITLE
输出内容与文档示例不一致

### ISSUE THREAD

**Issue by leslieeilsel** [guanguans/soar-php#9]
#### 测试环境：
- Windows 10
- soar 0.11.0
- Laravel 5.7
- PHP 7.2.8
- soar-php配置与[.soar.example](https://github.com/guanguans/soar-php/blob/master/.soar.example)相同

#### soar-php输出结果：
![soar-php](http://r.photo.store.qq.com/psb?/V12ol6gx2nrILn/2S3viJhWV8p1Gui0T7*jcqun2Aqp.rBfFoylB.ynYzw!/r/dFIBAAAAAAAA)
#### soar输出结果：
![soar](http://r.photo.store.qq.com/psb?/V12ol6gx2nrILn/nQiZxgaFMQBpA*axc*Zl5*yyz2iKgMIBs.W3E3Bx7Zw!/r/dL8AAAAAAAAA)
#### 测试代码：
```php
  $soar = new Soar();
  $sql ="SELECT * FROM `fa_user` `user` LEFT JOIN `fa_user_group` `group` ON `user`.`group_id`=`group`.`id`;";
  echo $soar->score($sql);
```
不清楚那哪个环节出现问题。

**Comment by guanguans** [comment]
@leslieeilsel window 下确实有问题，详情可看 [soar 说明中的功能特点第一条](https://github.com/XiaoMi/soar#功能特点)

**Comment by leslieeilsel** [comment]
> @leslieeilsel window下确实有问题，详情可看[soar说明中的功能特点第一条](https://github.com/XiaoMi/soar#%E5%8A%9F%E8%83%BD%E7%89%B9%E7%82%B9)

#### 测试脚本：
```shell
echo 'SELECT * FROM `fa_user` `user` LEFT JOIN `fa_user_group` `group` ON `user`.`group_id`=`group`.`id`;' | C:\Soar\soar.exe  -online-dsn=selectuser:123456@127.0.0.1:3306/database  -test-dsn=root:leslie@127.0.0.1:3306/ifengxi  -log-output=D:\Laravue\ifengxi\Backend\storage\logs\soar.log  -log-level=7  -report-type=json
```
#### CMD中执行结果：
![cmd](http://r.photo.store.qq.com/psb?/V12ol6gx2nrILn/POYV*NgI5.eTDmtsZ8RUWc60AWHr.EH2CCJcakU.eRI!/r/dLYAAAAAAAAA)
#### PowerShell中执行结果：
![powershell](http://r.photo.store.qq.com/psb?/V12ol6gx2nrILn/oT0CxkvnfM1eXKRWvfHMlB..coUxqdQ.BfRJ46pgvwE!/r/dFQBAAAAAAAA)

### 同样的命令在不同的终端中执行结果不一样，PowerShell中是正确的结果。

PHP应该默认情况下会在cmd的环境下执行脚本，在cmd下要想拿到PowerShell的结果，可以在脚本前边加上`powershell `，所以命令就变成这样：
```shell
powershell <原命令>
```
***
#### 再进行测试：
![cmd](http://r.photo.store.qq.com/psb?/V12ol6gx2nrILn/A8i*zYdevFBVkfykjVnYoShZKqr0UwwvRI0XuQToroU!/r/dL4AAAAAAAAA)
#### 结果正确!

***

#### 再回到PHP代码中测试，因为是测试，直接在前面拼接上`powershell `：
![php](http://r.photo.store.qq.com/psb?/V12ol6gx2nrILn/CfVFjU4aqe3CcJSVbnMoVWAYXuh*EJzynfhpwxwRdbI!/r/dL8AAAAAAAAA)
运行之后，结果正确！

**Comment by guanguans** [comment]
@leslieeilsel 可否修复下代码，合并过来呢？

**Comment by leslieeilsel** [comment]
> @leslieeilsel 可否修复下代码，合并过来呢？

我想一下怎么弄！不一定搞得定！

**Comment by guanguans** [comment]
@leslieeilsel 幸苦了。

**Comment by guanguans** [comment]
@all-contributors please add @leslieeilsel for bug
